/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CobranzasRouteImport } from './routes/cobranzas'
import { Route as CuentaCorrienteRouteImport } from './routes/cuenta-corriente'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as ExtraordinariosRouteImport } from './routes/extraordinarios'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as LibroMayorRouteImport } from './routes/libro-mayor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VencimientosRouteImport } from './routes/vencimientos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobranzasRoute = CobranzasRouteImport.update({
  id: '/cobranzas',
  path: '/cobranzas',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaCorrienteRoute = CuentaCorrienteRouteImport.update({
  id: '/cuenta-corriente',
  path: '/cuenta-corriente',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraordinariosRoute = ExtraordinariosRouteImport.update({
  id: '/extraordinarios',
  path: '/extraordinarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroMayorRoute = LibroMayorRouteImport.update({
  id: '/libro-mayor',
  path: '/libro-mayor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VencimientosRoute = VencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/cobranzas': typeof CobranzasRoute
  '/cuenta-corriente': typeof CuentaCorrienteRoute
  '/equipo': typeof EquipoRoute
  '/extraordinarios': typeof ExtraordinariosRoute
  '/importar': typeof ImportarRoute
  '/libro-mayor': typeof LibroMayorRoute
  '/login': typeof LoginRoute
  '/vencimientos': typeof VencimientosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/cobranzas': typeof CobranzasRoute
  '/cuenta-corriente': typeof CuentaCorrienteRoute
  '/equipo': typeof EquipoRoute
  '/extraordinarios': typeof ExtraordinariosRoute
  '/importar': typeof ImportarRoute
  '/libro-mayor': typeof LibroMayorRoute
  '/login': typeof LoginRoute
  '/vencimientos': typeof VencimientosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/cobranzas': typeof CobranzasRoute
  '/cuenta-corriente': typeof CuentaCorrienteRoute
  '/equipo': typeof EquipoRoute
  '/extraordinarios': typeof ExtraordinariosRoute
  '/importar': typeof ImportarRoute
  '/libro-mayor': typeof LibroMayorRoute
  '/login': typeof LoginRoute
  '/vencimientos': typeof VencimientosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/caja'
    | '/clientes'
    | '/cobranzas'
    | '/cuenta-corriente'
    | '/equipo'
    | '/extraordinarios'
    | '/importar'
    | '/libro-mayor'
    | '/login'
    | '/vencimientos'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/caja'
    | '/clientes'
    | '/cobranzas'
    | '/cuenta-corriente'
    | '/equipo'
    | '/extraordinarios'
    | '/importar'
    | '/libro-mayor'
    | '/login'
    | '/vencimientos'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/caja'
    | '/clientes'
    | '/cobranzas'
    | '/cuenta-corriente'
    | '/equipo'
    | '/extraordinarios'
    | '/importar'
    | '/libro-mayor'
    | '/login'
    | '/vencimientos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  CajaRoute: typeof CajaRoute
  ClientesRoute: typeof ClientesRoute
  CobranzasRoute: typeof CobranzasRoute
  CuentaCorrienteRoute: typeof CuentaCorrienteRoute
  EquipoRoute: typeof EquipoRoute
  ExtraordinariosRoute: typeof ExtraordinariosRoute
  ImportarRoute: typeof ImportarRoute
  LibroMayorRoute: typeof LibroMayorRoute
  LoginRoute: typeof LoginRoute
  VencimientosRoute: typeof VencimientosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranzas': {
      id: '/cobranzas'
      path: '/cobranzas'
      fullPath: '/cobranzas'
      preLoaderRoute: typeof CobranzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta-corriente': {
      id: '/cuenta-corriente'
      path: '/cuenta-corriente'
      fullPath: '/cuenta-corriente'
      preLoaderRoute: typeof CuentaCorrienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraordinarios': {
      id: '/extraordinarios'
      path: '/extraordinarios'
      fullPath: '/extraordinarios'
      preLoaderRoute: typeof ExtraordinariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro-mayor': {
      id: '/libro-mayor'
      path: '/libro-mayor'
      fullPath: '/libro-mayor'
      preLoaderRoute: typeof LibroMayorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vencimientos': {
      id: '/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof VencimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  CajaRoute: CajaRoute,
  ClientesRoute: ClientesRoute,
  CobranzasRoute: CobranzasRoute,
  CuentaCorrienteRoute: CuentaCorrienteRoute,
  EquipoRoute: EquipoRoute,
  ExtraordinariosRoute: ExtraordinariosRoute,
  ImportarRoute: ImportarRoute,
  LibroMayorRoute: LibroMayorRoute,
  LoginRoute: LoginRoute,
  VencimientosRoute: VencimientosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
